###
# @name getClientes
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwiZXhwIjoxNzE2NTUzNTUzLCJ1c2VyIjoianVhbjEyMyIsInJvbGUiOiJDTElFTlRFIn0.CXjRR67bIResarlpUBGcitZ_am0gqIq5AvwfpHKDwkVHCCjeAagQ5ojr5JIZZ0E4xs36bVc5a3-dyeX5GTy_Ziu9P58gcMkMPC4X9U3kn3dRD0fwmpftit4d1OQt9BdVFcNCmjUkIAN8otffhrfRKKG8fXfjbcCVl6HrmaFbkkQibRahfYiAIoMGVPtMWHKuEuDcqQbGp-O02G8mF0r1UZRcMjC4mchVI3kZm1HrmZWqfCMxQOQTgb-3oLExzL5qxS_R0ZpgHJmn_06CCpwlzuSNdJqidGhrJANmkGmq0jRJUMsXWvAnaBuXk2bvZzXuVMUdXMFXi6Obo9G0U_ZqbA

query getClientes {
  getAllClientes {
    clienteId
    nombre
    apellidos
  }
}

###
# @name getClienteById
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwiZXhwIjoxNzE2NTczODEwLCJ1c2VyIjoianVhbjEyMyIsInJvbGUiOiJDTElFTlRFIn0.GfMqikXCvVkmy0lxZ_-1xXUE7VVxduEW0Rb0FVyNYk9kLmzq0LPKv1L07LAlUVKp713wTM_9Xm1DmAlfk1dGaBbewEV9E2wEBdCaigFRGudZaLD5z4YodqiT12gS9DnGBdw6T52v7sM8IKFYRX2C17x7chfqvyTv-Y0u8ZoeSmPf3PKrboEQuF6InpGAnbq0JZsdeuc4Sxz8gJzdfszSSMFtdkxRPzazoMnHMbuTQ6U7brHUwYv539jmlSMn6ZtrU4CRf84YgyEdnyt5kC2bLPYY67wP5-QDRKwt1C7zYlfuPLpbD2E4OP1eXI9Pz1zUFFOYJ8FkGN5Xs0DLyb4nkQ

query getClienteById {
  getClienteById(clienteId: 1) {
    clienteId
    nombre
    apellidos
    numero
    usuario {
        username
        correo
        password
    }
  }
}

###
# @name getClienteByUserId
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwiZXhwIjoxNzE2NjU3MjQzLCJ1c2VyIjoianVhbjEyMyIsInJvbGUiOiJDTElFTlRFIn0.EaGd9zcg8zyMpbPs8hg4_6ioR_9x43dmUeTS4WRc6FHNE00NgYMIEbJV4Ex4_yB_-UQHdAh6sghR9klcBPb0IFgr5H5aGWfOhU-mtN04eLH1LynFFbSY4IT3Ino8zjIbWzOZrBaz42_uDjUj5Sr8Na-inDUJhfD2DGiwVoZRySjEjp2L9VVTfUI9Ra_wquug-ZUkJiEjMpCFSrf93hq9thLIfB6SMSBXhYp89okr1sbD_fKuDEFdgHHivBJgevaGVhrfeBxGccz3P2cUI3WemjCP8a6ALPLXMz57AvfeIiCprpSE6zPMDjVizZi6PscVNcthyTSauYqEj55QQwpqdg

query getClienteByUserId {
  getClienteByUserId {
    clienteId
    nombre
    apellidos
    numero
    usuario {
        username
        correo
        password
    }
  }
}

###
# @name deleteCliente
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

mutation deleteCliente {
  deleteCliente(clienteId: 38)
}

###
# @name updateCliente
PUT http://localhost:8080/cliente/update
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtYXJjb3MxMjMiLCJleHAiOjE3MTY1NzAwMzMsInVzZXIiOiJtYXJjb3MxMjMiLCJyb2xlIjoiUFJPRiJ9.K3Cjyuazy33lN--vYgT0clBUI6NZ8gR5N1tigE9mw-dKB52OK6f64akC9FQMuDsrRP4bOqEDXSCK-Y_-xuBwfvGtRbgN0t7ISb5-bdYbLvoKY-QysFl8t46pYbHgpjV6vQMSDkLpXOZK2mHDWSZl8zdZVE8Mxyo-wVvxrlC_kBvIy0UUz2xvlbyuKOe34EJZzNYhXx4gv37GSXroIG2RxPPtQc7EvztMwsZdMH8JyY_2jnwECFBvg9mQMTUG9Zut1AQN9KkXxsYmzGAoNRiDwx5nw9cYvT4LLVtjjxN4mSgLICx7H4g6B9mv7MUo1YOB8nkDFRnhsZR_g84C__a_PQ
Content-Type: application/json

{
  "clienteId": 1,
  "nombre": "Lucas II",
  "apellidos": "Ramirez Hernandez",
  "numero": "633928272",
  "usuario": {
    "userId": 1,
    "username": "lucas90",
    "correo": "sasaji2004@gmail.com",
    "password": "2dam",
    "activado": false,
    "fechaEnvio": null,
    "codigoActivacion": "",
    "role": "CLIENTE"
  }
}
