###
# @name getContratos
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getContratos {
  getAllContratos {
    contratoId
    cliente {clienteId}
    profesional {profesionalId}
    servicio {servicioId}
    fechaInicio
    fechaFin
    estado
  }
}

###
# @name getContratosByCliente
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwiZXhwIjoxNzE2NjU5ODUyLCJ1c2VyIjoianVhbjEyMyIsInJvbGUiOiJDTElFTlRFIn0.ZGasbWc_rWu8YD-jzJEEAXLeF9slybvKseYb5Hsm-A81i--uxY-S6NPAqM2oRPhffyKTEo_qAszULlMiBkhGCvmSkB6XouIgcHlz0FSi7ILloil8HSrMTs5N4vUkrRmomoSLCu4CNsR5xGYzuKhDQbkPWXOLnMucuOZ1w5x_Ruxl_jGShuspxJS8tDaILF3f19UnWljctk10LEPy7EFIdoSINzs0hCXtvtsSrKJW1DSRUgoVC-IQftedT5kpqVcXE4wsry-kA-v2aeCwJZZhGqSx8JSPkZG7ifL6czfoWAZT_-bVy528LdTG-DHkn7keMsiBOuRcT2jXOl02C2AvbQ

query getContratosByCliente {
  getContratosByCliente {
    profesional {nombre}
    servicio {nombre, tarifaBase}
    estado
  }
}

###
# @name getContratosByProfesional
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtYXJjb3MxMjMiLCJleHAiOjE3MTY2NTk5NTUsInVzZXIiOiJtYXJjb3MxMjMiLCJyb2xlIjoiUFJPRiJ9.hYt3zWRO94V0RQko-b-WwoLAHMFzNujBU8vbIt3CSbg2wSv_G6WXoWapH_sGEjYibkpnYc9zn48b94e27ul9ETWIB8sBwftZe5XUFBVHAfCMDO826FWmqGFYPpmzRNp__xDUV4yJLTW23Sjiw7udu3UEqYw5qLxxEklxchC9wdAOUn0w0LH5kO7oaOWL0UWkpfF_9HhTNNjHWtBQsJ_NEzcXP2lzdRpL1eFO_UaNE33OXB3nmxvtWS977UDq8MO9c0cfa-hBbWMBNn8LI_iNQftGhbZn7DQkS9hqi_wZMmmR9vDK2sMgisVqgQ37FPYHT_CWAXL14wk-BWXHrhj-Bw

query getContratosByProfesional {
  getContratosByProfesional {
    cliente {nombre}
    servicio {nombre, tarifaBase}
    estado
  }
}

###
# @name getContratosByEstado
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getContratosByEstado {
  getContratosByEstado(estado: "pendiente") {
    cliente {nombre}
    servicio {nombre}
    estado
  }
}

###
# @name getContratoById
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getContratoById {
  getContratoById(contratoId: 1) {
    contratoId
    cliente {nombre}
    servicio {nombre, descripcion, tarifaBase}
    fechaInicio
    fechaFin
    estado
  }
}

###
# @name updateContrato
PUT http://localhost:8080/contrato/updateEstado?contratoId=1&estado=Inactivo
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

###
# @name addContrato
POST http://localhost:8080/contrato/add
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwiZXhwIjoxNzE2Njc0NTA5LCJ1c2VyIjoianVhbjEyMyIsInJvbGUiOiJDTElFTlRFIn0.NrwUSw0kO_GIO_v5T8FijRJhjlGmxqIEscZq4JCHhqQ7P5rczTPZprvBj7ADos0UhM5euGPte3a5udhDQuSWvCLAhoED8qAZNGt4QzeYzkxPh3_FiChxntQ9nY-iU6qar51P3-6v10aVVV0w0taHJ2uWRvVgQj1M26cUVNlDr66MeiVUimKELp0msF-XSErk11vxv7e7LwdekI8KBfIGAC2MaOUXkrb6iyPs4obrDhGBHMrpvb9civMYX9U4R9F0iv_nzJwTsX7r05KlJGP62keyirLgAkoGIK3VIp81wF4VFHuuTlMOeogi5Zu1r4vBFArNjIWUZ7mWA1vKMDcBEg
Content-Type: application/json

{
  "profesional": {
    "profesionalId": 1
  },
  "servicio": {
    "servicioId": 1,
    "nombre": "Nombre del Servicio",
    "tarifaBase": 10.1
  },
  "fechaInicio": "2024-06-01",
  "estado": "Activo"
}