###
# @name getContratos
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getContratos {
  getAllContratos {
    contratoId
    cliente {clienteId}
    profesional {profesionalId}
    servicio {servicioId}
    fechaInicio
    fechaFin
    estado
  }
}

###
# @name getContratosByCliente
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getContratosByCliente {
  getContratosByCliente(clienteId: 1) {
    profesional {nombre}
    servicio {nombre, tarifaBase}
    estado
  }
}

###
# @name getContratosByProfesional
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getContratosByProfesional {
  getContratosByProfesional(profesionalId: 1) {
    cliente {nombre}
    servicio {nombre, tarifaBase}
    estado
  }
}

###
# @name getContratosByEstado
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getContratosByEstado {
  getContratosByEstado(estado: "pendiente") {
    cliente {nombre}
    servicio {nombre}
    estado
  }
}

###
# @name getContratoById
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getContratoById {
  getContratoById(contratoId: 1) {
    contratoId
    cliente {nombre}
    servicio {nombre, descripcion, tarifaBase}
    fechaInicio
    fechaFin
    estado
  }
}

###
# @name updateContrato
PUT http://localhost:8080/contrato/updateEstado?contratoId=1&estado=Inactivo
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

###
# @name addContrato
POST http://localhost:8080/contrato/add
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw
Content-Type: application/json

{
  "profesional": {
    "profesionalId": 2
  },
  "servicio": {
    "servicioId": 1,
    "nombre": "Nombre del Servicio",
    "tarifaBase": 10.1
  },
  "fechaInicio": "2024-06-01",
  "estado": "Activo"
}