###
# @name getFacturas
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getFacturas {
  getAllFacturas {
    facturaId
    cliente { clienteId }
    profesional { profesionalId }
    servicio { servicioId }
    precio
    estado
  }
}

###
# @name getFacturasByCliente
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwiZXhwIjoxNzE2NjU3MjI0LCJ1c2VyIjoianVhbjEyMyIsInJvbGUiOiJDTElFTlRFIn0.bB70MHK6jbGNE8acmhhli7Ma0YnMUgqFfzDOPEON4pb9Loopm8tuqkuzX0yIoo43Bq6ehME3vZIqtTmqCiYD_SB2uvCQ3ZXR3Q34yr_bRC7Z9q8al_i1RhIJ1slOQZrskj3xbGMLzaI2RfPkjx31snwgzC7T1HlNpcMBk_P3qBBYHGREmczPHq7O5A9y2VcnAh4xbwxsy3yen0d1xlc4WAUVT8wVYk3eYO7cI9c2dG9s2d8lC8PkN2vh4ei4Qt0Qyx5h9Qdwjem5mAuVmGo2GOpbCdlOe0daXI4MhBn7DhJAjk1LxJRHb9HLCnFw_vDOh2Ny37xoRohHsR9OWJXl0A

query getFacturasByCliente {
  getFacturasByCliente {
    profesional { nombre }
    servicio { nombre }
    precio
    estado
  }
}

###
# @name getFacturasByProfesional
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtYXJjb3MxMjMiLCJleHAiOjE3MTY2NjAzNTEsInVzZXIiOiJtYXJjb3MxMjMiLCJyb2xlIjoiUFJPRiJ9.N9ecNwGlSkDKiyEU88Vff7hDuSrT1Dz-VQs_Nq12qJAU0pwuPA_7XHLm-a_R-5GY8OST0Bhr1jTI6HZxawqfnWIz46bPDVfQud8ONDCotap_EMPoVysaAugM2lbw1HmvhEBjYz-8g1XbV20Euo7rBl0atyz5rgwgrzTcQS_VDdxJhA2GMZrlMxgIjR7Agy3RQFQjCJ-Pri6NEgbYgIXcyCH0Lnm6IY6INympNEKKZ9KP-9A1pol33d23_cRCEsxJUOH7YDDzTjBclRT7NFUkwieGITg_e269jgcnK9k7uuC9LmEnS2N8DNQZl4ZnvuyqDMcRenyi-nhebgrRidBN2A

query getFacturasByProfesional {
  getFacturasByProfesional {
    cliente { nombre }
    servicio { nombre }
    precio
    estado
  }
}

###
# @name getFacturaById
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getFacturaById {
  getFacturaById(facturaId: 1) {
    facturaId
    profesional { nombre, apellidos }
    servicio { nombre }
    precio
    estado
  }
}

###
# @name updateFacturaEstado
PUT http://localhost:8080/factura/updateEstado?facturaId=13
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwiZXhwIjoxNzE2NzM5ODczLCJ1c2VyIjoianVhbjEyMyIsInJvbGUiOiJDTElFTlRFIn0.CQQXlavWmmUL557_pWS8eP3RuYXV5DR_Lc0PESREFnqSxioIH3dQlavYzEhQ1rT-ZMCntnW3nsiD-Z6_w1Jb31NxooXmsVyP3_ZPyCK7xUWdRvvDGmBLlFPQ6Q_3pFIOIIkEMjjFxkvxiabtht3mpouQmyVW0xbqx0wtkVSsME6A7tsdhRYoxnvC40d4L9LPQnDNqsCn72mxlHLl1Bpzz82YNGW6EyPI-7L5XFic_4qtS4q4Jyqvd9ALUix65eJfL3FLWsQJ8bKOIng-nKmgbk99LMW0WdtnPwUEWSw-nTM9VW9NzXdwD4ts2PRgTyklXxEiJcUStPLYfNb38itaIw
###
# @name addFactura
POST http://localhost:8080/factura/add
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtYXJjb3MxMjMiLCJleHAiOjE3MTY3Mzk3NDQsInVzZXIiOiJtYXJjb3MxMjMiLCJyb2xlIjoiUFJPRiJ9.GvFIzq56L3KX0Vhg1028NPXdihADjPmsbV4onNZ_UJQUkGf8aRTNddSI042o3Vu4fxrmiMWwcPsIQPn3KSAbN2a5q6hUgs4pin6l38M_VEps60Tdu_rHlxDM7PbIdPKV4WkckkJqkZnI0VFPvV9rDvkHUQf4aXa1w4D5QJRc_wZAehvRAK-Y4dzlEOXPobJH9FUHYtoavS2ECaOMy5W2AjBJ8imJVRgSnJJ5ko80WTpHiZJ01vpxxuAgTOAx1j_AAHlPTHX_-7eNsv4CYHFU6kN_3MW63_blV1_7kFbsNEUd296uOQT2RxV9T7YtJcW7thFEB6C55DtNuS9JrLU5tA
Content-Type: application/json

{
  "cliente": {
    "clienteId": 1
  },
  "servicio": {
    "servicioId": 2,
    "tarifaBase": 10.0
  },
  "materiales": [
    {
      "material": {
        "materialId": 1,
        "nombre": "Material 1",
        "descripcion": "Descripción del Material 1",
        "precio": 10.0
      },
      "cantidad": 5
    },
    {
      "material": {
        "materialId": 2,
        "nombre": "Material 2",
        "descripcion": "Descripción del Material 2",
        "precio": 20.0
      },
      "cantidad": 3
    }
  ],
  "precio": 1.0
}
