###
# @name getAllFavoritosByCliente
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getAllFavoritosByCliente {
  getAllFavoritosByCliente {
    clienteId
    profesional {
        profesionalId
        nombre
        valoracion
    }
  }
}

###
# @name deleteFavorito
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwiZXhwIjoxNzE2NjU5MDAyLCJ1c2VyIjoianVhbjEyMyIsInJvbGUiOiJDTElFTlRFIn0.TIxwvfeTbYNauxsNNhHmx66eoOwTwPdwBLq3eV7DEzl-duu2XetYWRio2ChyOsTcF4uY9-uxkdAw6Zmzc3pVrtkReJkzpr7cDnDcoV9vBTZ0oe5UlJkJmInp6Xm0kvFMtaJYTwFDlXpt1QUUrOj-YirSuhHFTvtNixQhaCjyohpsQEXHhHXNJv7pxDGdPJ7PK6EzqdxtIgWEMiEgvjXAdlVnA4lvrWMzW2NgPEQk4Ipg19aUPSVIsADnowvzdWCw5j874TTirKpq1UgibkLPCI5WhMJo-aQt-Km0lyqSONi6fjn7cShks4B9uGIY64YdoBX5F5KKj9zmgte57ZG43w

mutation deleteFavorito {
  deleteFavorito(profesionalId: 3)
}

###
# @name addFavorito
POST http://localhost:8080/favoritos/add?profesionalId=3
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwiZXhwIjoxNzE2NjU5MDAyLCJ1c2VyIjoianVhbjEyMyIsInJvbGUiOiJDTElFTlRFIn0.TIxwvfeTbYNauxsNNhHmx66eoOwTwPdwBLq3eV7DEzl-duu2XetYWRio2ChyOsTcF4uY9-uxkdAw6Zmzc3pVrtkReJkzpr7cDnDcoV9vBTZ0oe5UlJkJmInp6Xm0kvFMtaJYTwFDlXpt1QUUrOj-YirSuhHFTvtNixQhaCjyohpsQEXHhHXNJv7pxDGdPJ7PK6EzqdxtIgWEMiEgvjXAdlVnA4lvrWMzW2NgPEQk4Ipg19aUPSVIsADnowvzdWCw5j874TTirKpq1UgibkLPCI5WhMJo-aQt-Km0lyqSONi6fjn7cShks4B9uGIY64YdoBX5F5KKj9zmgte57ZG43w