###
# @name getProfesionales
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtYXJjb3MxMjMiLCJleHAiOjE3MTY1NzAwMzMsInVzZXIiOiJtYXJjb3MxMjMiLCJyb2xlIjoiUFJPRiJ9.K3Cjyuazy33lN--vYgT0clBUI6NZ8gR5N1tigE9mw-dKB52OK6f64akC9FQMuDsrRP4bOqEDXSCK-Y_-xuBwfvGtRbgN0t7ISb5-bdYbLvoKY-QysFl8t46pYbHgpjV6vQMSDkLpXOZK2mHDWSZl8zdZVE8Mxyo-wVvxrlC_kBvIy0UUz2xvlbyuKOe34EJZzNYhXx4gv37GSXroIG2RxPPtQc7EvztMwsZdMH8JyY_2jnwECFBvg9mQMTUG9Zut1AQN9KkXxsYmzGAoNRiDwx5nw9cYvT4LLVtjjxN4mSgLICx7H4g6B9mv7MUo1YOB8nkDFRnhsZR_g84C__a_PQ

query getProfesionales {
  getAllProfesionales {
    profesionalId
    nombre
    apellidos
    numero
    experiencia
    oficio
    disponibilidad
    valoracion
  }
}

###
# @name getProfesionalesByExperiencia
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtYXJjb3MxMjMiLCJleHAiOjE3MTY1NTM3MzEsInVzZXIiOiJtYXJjb3MxMjMiLCJyb2xlIjoiUFJPRiJ9.CYTYrnbxYsd6lDa0-ZNvn5CBT9xz36x4kNxkPeWcrQOpKQ8XCTlYgYZ0jLVUH94C2i_eC7nlKhSAWJMiwBwUZ2EftDM0L_CVvOWr0X57ybmA7WHA_zGnn10jtE0sQQKWrJm8beVNrwBNISYJKycZtSraeIDEHh0mhyRUW_Fm2SeFmnrwynVR6k53-Qz8UwUy5VJ_R-GYlIrBxrdcUFpjptpteKNvyQuHu0kXh_p4u0hZLynQtdszlRhclwlhednxx8REWHireCrcwS1qpuQvwwUVcUvxPeDns2_jYyq6_O3FWeKhKmtlA-pUbM4xEuSteJ7H1knyOBsaNSC_otaakg

query getProfesionalesByExp {
  getAllProfesionalesByExp(experiencia: 5) {
    profesionalId
    nombre
    apellidos
    numero
    experiencia
    oficio
    disponibilidad
    valoracion
  }
}

###
# @name getProfesionalesByOficio
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getProfesionalesByOficio {
  getAllProfesionalesByOficio(oficio: "Fontanero") {
    profesionalId
    nombre
    apellidos
    numero
    experiencia
    oficio
    disponibilidad
    valoracion
  }
}

###
# @name getProfesionalesByDisponibilidad
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getProfesionalesByDisp {
  getAllProfesionalesByDisp(disponibilidad: "Tarde") {
    profesionalId
    nombre
    apellidos
    numero
    experiencia
    oficio
    disponibilidad
    valoracion
  }
}

###
# @name getProfesionalesByValoracion
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getProfesionalesByVal {
  getAllProfesionalesByVal(valoracion: 4) {
    profesionalId
    nombre
    apellidos
    numero
    experiencia
    oficio
    disponibilidad
    valoracion
  }
}

###
# @name getProfesionalById
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtYXJjb3MxMjMiLCJleHAiOjE3MTY1NTM3MzEsInVzZXIiOiJtYXJjb3MxMjMiLCJyb2xlIjoiUFJPRiJ9.CYTYrnbxYsd6lDa0-ZNvn5CBT9xz36x4kNxkPeWcrQOpKQ8XCTlYgYZ0jLVUH94C2i_eC7nlKhSAWJMiwBwUZ2EftDM0L_CVvOWr0X57ybmA7WHA_zGnn10jtE0sQQKWrJm8beVNrwBNISYJKycZtSraeIDEHh0mhyRUW_Fm2SeFmnrwynVR6k53-Qz8UwUy5VJ_R-GYlIrBxrdcUFpjptpteKNvyQuHu0kXh_p4u0hZLynQtdszlRhclwlhednxx8REWHireCrcwS1qpuQvwwUVcUvxPeDns2_jYyq6_O3FWeKhKmtlA-pUbM4xEuSteJ7H1knyOBsaNSC_otaakg

query getProfesionalById {
  getProfesionalById(profesionalId: 1) {
    profesionalId
    nombre
    apellidos
    numero
    experiencia
    oficio
    disponibilidad
    usuario {
        username
        correo
        password
    }
  }
}

###
# @name getProfesionalParaCliente
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getProfesionalParaCliente {
  getProfesionalById(profesionalId: 1) {
    nombre
    apellidos
    numero
    experiencia
    oficio
    disponibilidad
    valoracion
  }
}

###
# @name getProfesionalNombre
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query getProfesionalNombre {
  getProfesionalById(profesionalId: 1) {
    nombre
  }
}

###
# @name deleteProfesional
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYXNhamkiLCJleHAiOjE3MTY1NTI0NjMsInVzZXIiOiJzYXNhamkiLCJyb2xlIjoiQURNSU4ifQ.oKVsxxOFpw-NHm1WDw0owzitgeWb1nFlWtZYMdJIdyLybC10Ae-Zr-ihbbV9QiQMl4XM1lXEAdMzZvuAdRcaz_UV-baG-zS0_8sQzKuhu9Me36jCy_o3_Q24W5-_QEoBIkvy6zxeekITxnxnropG_4Y57f1Jhx2jfN0kpEg4kuhyrlW1vMiu--ur016ly9Vu9zKN4jHT-2gUwIvN_kBpE5Atg5zW65sbrXJPbHT4a6kqrRMqRTSnHmsvY8Vs90W8jT_wwWd-gwuObVg7vRcgwsHu5LCKNOh9Czb5nDEnYiGgCEbISVYec_MOtLoZl7_z4ecIAMLr7Z6-YT--ciVYzA

mutation deleteProfesional {
  deleteProfesional(profesionalId: 18)
}

###
# @name updateProfesional
PUT http://localhost:8080/profesional/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

{
  "profesionalId": 1,
  "nombre": "Fernando II",
  "apellidos": "Montoya Gutierrez",
  "numero": "622937362",
  "experiencia": 15,
  "oficio": "Pintor",
  "disponibilidad": "Mañana",
  "valoracion": 3,
  "usuario": {
    "userId": 4,
    "username": "fernando23",
    "correo": "sasaji2004@gmail.com",
    "password": "2dam",
    "activado": false,
    "fechaEnvio": null,
    "codigoActivacion": "",
    "role": "PROF"
  }
}

###
# @name updateProfesionalVal
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw

query updateProfesionalVal {
  updateProfesionalVal(profesionalId: 3, valoracion: 1)
}