# @name loginAdmin
GET http://localhost:8080/login?
    username=sasaji&
    password=1234

###
# @name registroCliente
POST http://localhost:8080/registro/cliente
Content-Type: application/json

{
  "clienteId": 0,
  "nombre": "Lucas",
  "apellidos": "Ramirez Hernandez",
  "numero": "633928272",
  "usuario": {
    "userId": 0,
    "username": "lucas90",
    "correo": "sasaji2004@gmail.com",
    "password": "2dam",
    "activado": false,
    "fechaEnvio": null,
    "codigoActivacion": "",
    "role": "CLIENTE"
  }
}

###
# @name activarUsuarioCliente
GET http://localhost:8080/registro/activacion?
    codigo=uRpbs0yJv4sRWmcfW663Sa9AbjB2LF6waX3HtODMSG0=

###
# @name loginCliente
GET http://localhost:8080/login?
    username=juan123&
    password=1234

###
# @name registroProfesional
POST http://localhost:8080/registro/profesional
Content-Type: application/json

{
  "profesionalId": 0,
  "nombre": "Fernando",
  "apellidos": "Montoya Gutierrez",
  "numero": "622937362",
  "experiencia": 15,
  "oficio": "Pintor",
  "disponibilidad": "Mañana",
  "valoracion": 3,
  "usuario": {
    "userId": 0,
    "username": "fernando23",
    "correo": "samper7804@gmail.com",
    "password": "2dam",
    "activado": false,
    "fechaEnvio": null,
    "codigoActivacion": "",
    "role": "PROF"
  }
}

###
# @name activarUsuarioProfesional
GET http://localhost:8080/registro/activacion?
    codigo=uRpbs0yJv4sRWmcfW663Sa9AbjB2LF6waX3HtODMSG0=

###
# @name loginProfesional
GET http://localhost:8080/login?
    username=marcos123&
    password=1234

