###
# @name getValoracionesByProf
GET http://localhost:8080/valoracion
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtYXJjb3MxMjMiLCJleHAiOjE3MTY2NTc3MzUsInVzZXIiOiJtYXJjb3MxMjMiLCJyb2xlIjoiUFJPRiJ9.Gfk9MQJf4eox9aCP7Mh0SGrUhxMzzc2dcCBhgBoQBjnGoKQvmj47E5YRw6_Gb-b6PRm95PJD17zMULGWDfAGimLTGS8Bo44SjZZcge17F1-1AfrzsuYMA8QT_arOz_iQKINFur-2AiG3zLydo7A1mXRt3rfbp03E4Bz6LU3qHdbSrrtrouDkJ5CPPUKJoumc5lWiHBa--oj7ShajDU-rrhEhXvlVZe2oBddi8MCq2LeNuGi9Hg8wLG9Uqvmw1l0Ya5UT2jpPHcV4FtNJU4PA9hNA0OO2EKyEEgwYZi3iEQCPnHy0u5o1bggO7gZRttUKxWBarACyaBTu2jfzXPQA_g

###
# @name addValoracion
POST http://localhost:8080/valoracion/add
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxNTI1NjQ0NywidXNlciI6ImFkbWluIiwicm9sZSI6IkFETUlOIn0.yozJt2H7A1wVeQ-zXIecf759leu4JvdxtQPvnf5DOW5Agp6x-wwbMLxhn4irjuejpIevW_Envx4O_KO_Abx1UZdi4YzD4Zr0d2DJrsekCtPjFeomMgf_2_OBh1J4-rtfmMbff5CMjXbajARh7NdlbzeCZk_YPNDdLEO3WTw1SMFdNX69pG9o_DoJaL5ZXHHJxPGDjFMsxB64al4dlMSXy9Npme4HkJpPM36k4WEjc-6SEbouJifoL8uMisCUGbbx-GAFlMT3pWobuHOoCJmpC7vpQxys605VRkPxDSPHtap2zblDPAyNR6CCRRqvx3UmsXCsnZVcPnzazPyLPc3ykw
Content-Type: application/json

{
  "nombreCliente": "Juan",
  "apellidoCliente": "Luque de Tena",
  "estrellas": 5,
  "descripcion": "Estupendo servicio, profesional muy puntual y amable"
}

